### ISSUE TITLE
Go ahead and change the readme to at markdown file

### ISSUE THREAD

**Issue by jameswagoner** [zavaboy/challonge-wp#1]

**Comment by zavaboy** [comment]
Sorry, I know I'm more than a year late on this reply.

The readme file is a flavor of Markdown, sometimes referred to as [quasi-Markdown](https://markjaquith.wordpress.com/2007/03/16/plugin-directory/), used in the [plugin directory on WordPress.org](https://wordpress.org/plugins/). Because of this and the directory requires it to be a `.txt` file, I'm not going to change it to a Markdown file. If all this were not the case, I'd certainly make it a proper Markdown file.
